/* ═══════════════════════════════════════════════════════════════
   LEVELS — array populated by files in /levels/*.js
   Add a new level: create levels/level_XX.js, call LEVELS.push({...})
   ═══════════════════════════════════════════════════════════════ */

const LEVELS = [];

/* ── Shared buggy code helpers ──────────────────────────────── */
// Mettre la bibliothèque de bug ici. Pour certaines lignes, faire des erreurs canoniques.
// Du coup au début c'est une question de comprendre les bugs, à terme, c'est simplement une question de le résoudre. 
// Type de bugs ez: parenthèses manquantes, typos dans les noms de variables, 
// oublis de lignes de code (lignes à uncomment), enlever des giga glitch (des char asci chelous à enlever)


function getBuggyGameOfLife() {
  return `// ── Conway's Game of Life ──────────────────────────
// generated by AI  •  do not modify  •  production ready ✓

let grid, nextGrid, cols, rows;
const CELL = 12;

function setup() {
  createCanvas(400, 400);
  cols = floor(width / CELL);
  rows = floor(height / CELL);

  // BUG 1: typo — 'widht' instead of 'width' causes ReferenceError
  let cellSize = widht / cols;

  grid     = makeGrid();
  nextGrid = makeGrid();

  for (let i = 0; i < cols; i++)
    for (let j = 0; j < rows; j++)
      grid[i][j] = random() < 0.3 ? 1 : 0;

  frameRate(12);
}

function draw() {
  background(8);

  noStroke();
  fill(57, 255, 20);
  for (let i = 0; i < cols; i++)
    for (let j = 0; j < rows; j++)
      if (grid[i][j])
        rect(i * CELL + 1, j * CELL + 1, CELL - 2, CELL - 2);

  for (let i = 0; i < cols; i++) {
    for (let j = 0; j < rows; j++) {
      const n = countNeighbors(i, j);
      if (grid[i][j]) {
        nextGrid[i][j] = (n === 2 || n === 3) ? 1 : 0;
      } else {
        nextGrid[i][j] = (n === 3) ? 1 : 0;
      }
    }
  }

  // BUG 3: swap commented out — grid never advances
  // [grid, nextGrid] = [nextGrid, grid];
}

function countNeighbors(x, y) {
  let sum = 0;
  for (let di = -1; di <= 1; di++) {
    for (let dj = -1; dj <= 1; dj++) {
      // BUG 2: missing skip for (0,0) — cell counts itself as a neighbor
      // if (di===0 && dj===0) continue;
      sum += grid[(x + di + cols) % cols][(y + dj + rows) % rows];
    }
  }
  return sum;
}

function makeGrid() {
  return Array.from({ length: cols }, () => new Array(rows).fill(0));
}

function mousePressed() {
  const col = floor(mouseX / CELL);
  const row = floor(mouseY / CELL);
  if (col >= 0 && col < cols && row >= 0 && row < rows)
    grid[col][row] = grid[col][row] ? 0 : 1;
}`;
}
